version = 1

[[analyzers]]
name = "python"
runtime_version = "3.x.x"
excludes = ["**/migrations/"]
    [analyzers.meta]
    flake8 = true

[[analyzers]]
name = "shell"

[[transformers]]
name = "black"
    [transformers.config]
    line-length = 88

[[transformers]]
name = "isort"
    [transformers.config]
    profile = "black"
