version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "2.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"